name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME}}
        password: ${{ secrets.DOCKER_HUB_PASSWORD}}

      name: Build the Docker image
      run: docker build . --file assignment_three/hello_world/Dockerfile --tag ${{ secrets.image_name }}:$(date +%s)

    - uses: docker/push-action@v3
      file: assignment_three/hello_world/Dockerfile
    - name: Push  the docker image
      push: true
      tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hi-world:latest