name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Building docker image
    - name: Build the Docker image
      run: docker build . --file assignment_three/hello_world/Dockerfile --tag ${{ secrets.image_name }}:$(date +%s)

    - uses: Pushing the docker image
    - name: Push the docker image
      run: docker push dhee1006/hi-world:v1.0.0
